CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: [0]
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 4
PRINT_FREQ: 10

DATASET:
  DATASET: loveda
  ROOT: data/
  TEST_SET: 'list/loveda/urban_rural/val.lst'
  TRAIN_SET: 'list/loveda/urban_rural/train.lst'
  TARGET_SET: 'list/loveda/rural/train.lst'
  NUM_CLASSES: 7
MODEL:
  NAME: pidnet_small
  NUM_OUTPUTS: 2
  PRETRAINED: "pretrained_models/imagenet/PIDNet_S_ImageNet.pth.tar"
LOSS:
  USE_OHEM: true
  OHEMTHRES: 0.9
  OHEMKEEP: 131072
  BALANCE_WEIGHTS: [0.4, 1.0]
  SB_WEIGHTS: 1.0
TRAIN:
  IMAGE_SIZE:
  - 1024
  - 1024
  BASE_SIZE: 2048
  BATCH_SIZE_PER_GPU: 6
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 20
  RESUME: true
  OPTIMIZER: sgd
  LR: 0.01
  WD: 0.0005
  MOMENTUM: 0.9
  NESTEROV: false
  FLIP: false
  MULTI_SCALE: false
  IGNORE_LABEL: 0
  SCALE_FACTOR: 16
  AUGMENTATION:
    ENABLE: true
    PROBABILITY: 0.5
    TECHNIQUES:
      HORIZONTAL_FLIP: false
      GAUSSIAN_BLUR: false
      MULTIPLY: false
      RANDOM_BRIGHTNESS: false
  DACS:
    ENABLE: true
    THRESHOLD: 0.968 
  GAN:
    ENABLE: false
    MULTI_LEVEL: false
TEST:
  IMAGE_SIZE:
  - 2048
  - 1024
  BASE_SIZE: 2048
  BATCH_SIZE_PER_GPU: 6
  FLIP_TEST: false
  MULTI_SCALE: false
  MODEL_FILE: 'output/loveda/pidnet_small_loveda/final_state.pt'
  OUTPUT_INDEX: 1